package br.com.thiagofesta.calculadora_logica;

import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 * Frame para utilização da calculadora
 * 
 * @author Thiago Felipe Festa
 * @version 1.0
 */
public class FCalculadoraLogica extends javax.swing.JFrame {

    /**
     * Armareza se o texto que está no jTextField é o resultado ou uma expressão
     */
    private boolean resultado;

    /**
     * Carrega os componentes, e seta o ícone do programa
     */
    public FCalculadoraLogica()
    {
            initComponents();
            this.setIconImage( new ImageIcon(getClass().getResource("/br/com/thiagofesta/resources/calculadora.png")).getImage() );
    }
    
    /**
     * Instância a classe CalculadoraLogica e resolve a expressao
     */
    private void resolve()
    {
            CalculadoraLogica calc = new CalculadoraLogica();

            if(jTextField.getText().compareTo("") > 0)
            {
                    if(calc.isValid(jTextField.getText()))
                    {
                            calc.tokenize(jTextField.getText());
                            jTextField.setText(calc.start());
                    }
                    else
                    {
                            jTextField.setText("EXPRESSÃO INVÁLIDA!");
                    }
                    
                    this.resultado = true;
            }
    }
    
    /**
     * Adiciona dado a expressão
     * @param texto Texto a ser adicionado no jTextField
     */
    private void setExpressao(String texto)
    {
            if(this.resultado)
            {
                   jTextField.setText("");
            }

            jTextField.setText(jTextField.getText() + texto + " ");
            this.resultado = false;
    }

    /**
     * Exibe cursor como seta normal, ou como mão
     * @param hover Se verdadeiro mouse está em cima do botão
     */
    private void setCursor(boolean hover)
    {
            Cursor cursor;

            if(hover)
            {
                   cursor = Cursor.getPredefinedCursor(Cursor.HAND_CURSOR);
            }
            else
            {
                    cursor = Cursor.getDefaultCursor();
            }

            setCursor(cursor);
    }
    
    /**
     * Seta o ícone do botão
     * @param label Label que receberá a imagem de fundo
     * @param caminho Nome do arquivo da imagem
     */
    private void setIcon(JLabel label, String caminho)
    {
            label.setIcon( new ImageIcon(getClass().getResource("/br/com/thiagofesta/resources/"+caminho)) );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jTextField = new javax.swing.JTextField();
        jNegacao = new javax.swing.JLabel();
        jConjuncao = new javax.swing.JLabel();
        jDisjuncao = new javax.swing.JLabel();
        jDisjuncaoExclusiva = new javax.swing.JLabel();
        jCondicional = new javax.swing.JLabel();
        jBicondicional = new javax.swing.JLabel();
        jLimpar = new javax.swing.JLabel();
        jTrue = new javax.swing.JLabel();
        jFalse = new javax.swing.JLabel();
        jParentesA = new javax.swing.JLabel();
        jParentesB = new javax.swing.JLabel();
        jIgual = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();
        jMenuItemCalculadora = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora L\u00f3gica");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jTextField.setEditable(false);
        jTextField.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField.setEnabled(false);

        jNegacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNegacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/thiagofesta/resources/negacao.png")));
        jNegacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jNegacaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jNegacaoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jNegacaoMousePressed(evt);
            }
        });

        jConjuncao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jConjuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/thiagofesta/resources/conjuncao.png")));
        jConjuncao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jConjuncaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jConjuncaoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jConjuncaoMousePressed(evt);
            }
        });

        jDisjuncao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDisjuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/thiagofesta/resources/disjuncao.png")));
        jDisjuncao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jDisjuncaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jDisjuncaoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jDisjuncaoMousePressed(evt);
            }
        });

        jDisjuncaoExclusiva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDisjuncaoExclusiva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/thiagofesta/resources/disjuncao_exclusiva.png")));
        jDisjuncaoExclusiva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jDisjuncaoExclusivaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jDisjuncaoExclusivaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jDisjuncaoExclusivaMousePressed(evt);
            }
        });

        jCondicional.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCondicional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/thiagofesta/resources/condicional.png")));
        jCondicional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCondicionalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCondicionalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCondicionalMousePressed(evt);
            }
        });

        jBicondicional.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBicondicional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/thiagofesta/resources/bicondicional.png")));
        jBicondicional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBicondicionalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBicondicionalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBicondicionalMousePressed(evt);
            }
        });

        jLimpar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/thiagofesta/resources/limpar.png")));
        jLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLimparMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLimparMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLimparMousePressed(evt);
            }
        });

        jTrue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTrue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/thiagofesta/resources/true.png")));
        jTrue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTrueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTrueMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTrueMousePressed(evt);
            }
        });

        jFalse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFalse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/thiagofesta/resources/false.png")));
        jFalse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jFalseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jFalseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jFalseMousePressed(evt);
            }
        });

        jParentesA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jParentesA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/thiagofesta/resources/parentesA.png")));
        jParentesA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jParentesAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jParentesAMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jParentesAMousePressed(evt);
            }
        });

        jParentesB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jParentesB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/thiagofesta/resources/parentesB.png")));
        jParentesB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jParentesBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jParentesBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jParentesBMousePressed(evt);
            }
        });

        jIgual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jIgual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/thiagofesta/resources/igual.png")));
        jIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jIgualMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jIgualMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jIgualMousePressed(evt);
            }
        });

        jMenuArquivo.setText("Arquivo");
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });

        jMenuArquivo.add(jMenuItemSair);

        jMenuBar.add(jMenuArquivo);

        jMenuSobre.setText("Sobre");
        jMenuItemCalculadora.setText("Calculadora");
        jMenuItemCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCalculadoraActionPerformed(evt);
            }
        });

        jMenuSobre.add(jMenuItemCalculadora);

        jMenuBar.add(jMenuSobre);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jNegacao, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jConjuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDisjuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDisjuncaoExclusiva, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCondicional, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBicondicional, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jParentesA, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jParentesB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTrue, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFalse, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jNegacao, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jConjuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDisjuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDisjuncaoExclusiva, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCondicional, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBicondicional, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jParentesB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jParentesA, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTrue, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFalse, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jNegacaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNegacaoMouseEntered
            setCursor(true);
            setIcon(jNegacao, "negacaoHover.png");
}//GEN-LAST:event_jNegacaoMouseEntered

    private void jNegacaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNegacaoMouseExited
            setCursor(false);
            setIcon(jNegacao, "negacao.png");
}//GEN-LAST:event_jNegacaoMouseExited

    private void jConjuncaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jConjuncaoMouseEntered
            setCursor(true);
            setIcon(jConjuncao, "conjuncaoHover.png");
}//GEN-LAST:event_jConjuncaoMouseEntered

    private void jConjuncaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jConjuncaoMouseExited
            setCursor(false);
            setIcon(jConjuncao, "conjuncao.png");
}//GEN-LAST:event_jConjuncaoMouseExited

    private void jDisjuncaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDisjuncaoMouseEntered
            setCursor(true);
            setIcon(jDisjuncao, "disjuncaoHover.png");
}//GEN-LAST:event_jDisjuncaoMouseEntered

    private void jDisjuncaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDisjuncaoMouseExited
            setCursor(false);
            setIcon(jDisjuncao, "disjuncao.png");
}//GEN-LAST:event_jDisjuncaoMouseExited

    private void jDisjuncaoExclusivaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDisjuncaoExclusivaMouseEntered
            setCursor(true);
            setIcon(jDisjuncaoExclusiva, "disjuncao_exclusivaHover.png");
}//GEN-LAST:event_jDisjuncaoExclusivaMouseEntered

    private void jDisjuncaoExclusivaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDisjuncaoExclusivaMouseExited
            setCursor(false);
            setIcon(jDisjuncaoExclusiva, "disjuncao_exclusiva.png");
}//GEN-LAST:event_jDisjuncaoExclusivaMouseExited

    private void jCondicionalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCondicionalMouseEntered
            setCursor(true);
            setIcon(jCondicional, "condicionalHover.png");
}//GEN-LAST:event_jCondicionalMouseEntered

    private void jCondicionalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCondicionalMouseExited
            setCursor(false);
            setIcon(jCondicional, "condicional.png");
}//GEN-LAST:event_jCondicionalMouseExited

    private void jBicondicionalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBicondicionalMouseEntered
            setCursor(true);
            setIcon(jBicondicional, "bicondicionalHover.png");
}//GEN-LAST:event_jBicondicionalMouseEntered

    private void jBicondicionalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBicondicionalMouseExited
            setCursor(false);
            setIcon(jBicondicional, "bicondicional.png");
}//GEN-LAST:event_jBicondicionalMouseExited

    private void jLimparMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLimparMouseEntered
            setCursor(true);
            setIcon(jLimpar, "limparHover.png");
}//GEN-LAST:event_jLimparMouseEntered

    private void jLimparMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLimparMouseExited
            setCursor(false);
            setIcon(jLimpar, "limpar.png");
}//GEN-LAST:event_jLimparMouseExited

    private void jTrueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTrueMouseEntered
            setCursor(true);
            setIcon(jTrue, "trueHover.png");
}//GEN-LAST:event_jTrueMouseEntered

    private void jTrueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTrueMouseExited
            setCursor(false);
            setIcon(jTrue, "true.png");
}//GEN-LAST:event_jTrueMouseExited

    private void jFalseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFalseMouseEntered
            setCursor(true);
            setIcon(jFalse, "falseHover.png");
}//GEN-LAST:event_jFalseMouseEntered

    private void jFalseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFalseMouseExited
            setCursor(false);
            setIcon(jFalse, "false.png");
}//GEN-LAST:event_jFalseMouseExited

    private void jParentesAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jParentesAMouseEntered
            setCursor(true);
            setIcon(jParentesA, "parentesAHover.png");
}//GEN-LAST:event_jParentesAMouseEntered

    private void jParentesAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jParentesAMouseExited
            setCursor(false);
            setIcon(jParentesA, "parentesA.png");
}//GEN-LAST:event_jParentesAMouseExited

    private void jParentesBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jParentesBMouseEntered
            setCursor(true);
            setIcon(jParentesB, "parentesBHover.png");
}//GEN-LAST:event_jParentesBMouseEntered

    private void jParentesBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jParentesBMouseExited
            setCursor(false);
            setIcon(jParentesB, "parentesB.png");
}//GEN-LAST:event_jParentesBMouseExited

    private void jIgualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jIgualMouseEntered
            setCursor(true);
            setIcon(jIgual, "igualHover.png");
}//GEN-LAST:event_jIgualMouseEntered

    private void jIgualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jIgualMouseExited
            setCursor(false);
            setIcon(jIgual, "igual.png");
}//GEN-LAST:event_jIgualMouseExited

    private void jNegacaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNegacaoMousePressed
            setExpressao("~");
}//GEN-LAST:event_jNegacaoMousePressed

    private void jConjuncaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jConjuncaoMousePressed
            setExpressao("^");
}//GEN-LAST:event_jConjuncaoMousePressed

    private void jDisjuncaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDisjuncaoMousePressed
            setExpressao("v");
}//GEN-LAST:event_jDisjuncaoMousePressed

    private void jDisjuncaoExclusivaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDisjuncaoExclusivaMousePressed
            setExpressao("x");
}//GEN-LAST:event_jDisjuncaoExclusivaMousePressed

    private void jCondicionalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCondicionalMousePressed
            setExpressao("->");
}//GEN-LAST:event_jCondicionalMousePressed

    private void jBicondicionalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBicondicionalMousePressed
            setExpressao("<->");
}//GEN-LAST:event_jBicondicionalMousePressed

    private void jParentesAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jParentesAMousePressed
            setExpressao("(");
}//GEN-LAST:event_jParentesAMousePressed

    private void jParentesBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jParentesBMousePressed
            setExpressao(")");
}//GEN-LAST:event_jParentesBMousePressed

    private void jTrueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTrueMousePressed
            setExpressao("T");
}//GEN-LAST:event_jTrueMousePressed

    private void jFalseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFalseMousePressed
            setExpressao("F");
}//GEN-LAST:event_jFalseMousePressed

    private void jLimparMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLimparMousePressed
            jTextField.setText("");
}//GEN-LAST:event_jLimparMousePressed

    private void jIgualMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jIgualMousePressed
            resolve();
}//GEN-LAST:event_jIgualMousePressed

    private void jMenuItemCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCalculadoraActionPerformed
            JOptionPane.showMessageDialog(this, "Calculadora criada para realizar expressões lógicas.\n\nCriada por Thiago Felipe Festa, aluno do 2º período\ndo curso de Sistemas de Informação da FASUL,\ncomo trabalho para a matéria LMC, dirigida pelo\nprofessor Fabio Alexandre Spanhol.", "Sobre a calculadora", 3);
}//GEN-LAST:event_jMenuItemCalculadoraActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
            this.dispose();
}//GEN-LAST:event_jMenuItemSairActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
            if(evt.getKeyCode() == evt.VK_T)
            {
                    setExpressao("T");
            }
            else if(evt.getKeyCode() == evt.VK_F)
            {
                    setExpressao("F");
            }
            else if(evt.getKeyCode() == evt.VK_N)
            {
                    setExpressao("~");
            }
            else if(evt.getKeyCode() == evt.VK_E)
            {
                    setExpressao("^");
            }
            else if(evt.getKeyCode() == evt.VK_O)
            {
                    setExpressao("v");
            }
            else if(evt.getKeyCode() == evt.VK_X)
            {
                    setExpressao("x");
            }
            else if(evt.getKeyCode() == evt.VK_C)
            {
                    setExpressao("->");
            }
            else if(evt.getKeyCode() == evt.VK_B)
            {
                    setExpressao("<->");
            }
            else if(evt.getKeyCode() == evt.VK_A)
            {
                    setExpressao("(");
            }
            else if(evt.getKeyCode() == evt.VK_S)
            {
                    setExpressao(")");
            }
            else if(evt.getKeyCode() == evt.VK_EQUALS)
            {
                    resolve();
            }
            else if(evt.getKeyCode() == evt.VK_DELETE)
            {
                    jTextField.setText("");
            }
            else if(evt.getKeyCode() == evt.VK_BACK_SPACE)
            {
                    if(jTextField.getText().length() >= 2)
                    {
                            jTextField.setText( jTextField.getText().substring(0, (jTextField.getText().length()-2) ) );
                    }
            }
    }//GEN-LAST:event_formKeyPressed
    
    /**
     * Inicia a FCalculadoraLogica
     * @param args Argumentos da linha de comando
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FCalculadoraLogica().setVisible(true);
            }
        });
    }

    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JLabel jBicondicional;
    private javax.swing.JLabel jCondicional;
    private javax.swing.JLabel jConjuncao;
    private javax.swing.JLabel jDisjuncao;
    private javax.swing.JLabel jDisjuncaoExclusiva;
    private javax.swing.JLabel jFalse;
    private javax.swing.JLabel jIgual;
    private javax.swing.JLabel jLimpar;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemCalculadora;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JLabel jNegacao;
    private javax.swing.JLabel jParentesA;
    private javax.swing.JLabel jParentesB;
    private javax.swing.JTextField jTextField;
    private javax.swing.JLabel jTrue;
    // Fim da declaração de variáveis//GEN-END:variables

}
